### ISSUE TITLE
Swift 2

### ISSUE THREAD

**Issue by raphamzn** [cemolcay/MaterialCardView#6]
Hello,

I sent my application using the card material to Apple Store and has been approved, but the download and run the same closes without reasons.

The problem does not occur in the simulator and in my development phone.

To reproduce the error you must generate a version of app.ipa on ad hock mode and install on your phone that the error occurs.

The error is in the method:
    func defaultInit () {
        h = 0
        appeareance = defaultAppeareance()

```
    contentView = UIView(superView: self)
    addSubview(contentView)
}
```

I need help!!!
Thanks.

**Comment by jayporta** [comment]
I cloned the project and opened it in XCode 7.1. I was immediately presented with an error for your required initializers. Maybe that was the problem? I've fixed it. This is my first time using GitHub. I committed the change to master. I hope that works.

**Comment by raphamzn** [comment]
I solved this error with change in lifecycle: 

```
// MARK: Lifecylce
override init (frame : CGRect) {
    super.init(frame : frame)

    contentView = UIView(superView: self)
    defaultInit()
}

convenience init () {
    self.init(frame:CGRect.zero)
}

required init(coder aDecoder: NSCoder) {
    fatalError("This class does not support NSCoding")
}

func defaultInit () {
    h = 0
    appeareance = defaultAppeareance()
    addSubview(contentView)
}
```
